apiVersion: v1
kind: Secret
metadata:
  name: mysql-bucket-uri
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  MYSQL_BUCKET_URI: {{ .Values.backup.bucket_uri | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-mysql
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  AWS_DEFAULT_REGION: {{ .Values.backup.aws_default_region | b64enc }}
---
